In [2]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

In [3]:
df = pd.read_csv('F:\\FASTAPI\\PatientsManagementSystem\\insurance.csv')

In [4]:
df.head()

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
0,67,119.8,1.56,2.92,False,Jaipur,retired,High
1,36,101.1,1.83,34.28,False,Chennai,freelancer,Low
2,39,56.8,1.64,36.64,False,Indore,freelancer,Low
3,22,109.4,1.55,3.34,True,Mumbai,student,Medium
4,69,62.2,1.60,3.94,True,Indore,retired,High

In [5]:
df.sample(5)

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
54,75,54.5,1.61,3.320000,True,Lucknow,retired,High
73,69,84.3,1.62,2.220000,True,Kolkata,retired,High
97,52,60.8,1.80,44.860000,False,Hyderabad,freelancer,Low
43,72,85.7,1.71,1.560000,False,Chennai,retired,Medium
14,49,89.3,1.65,13.505166,False,Kota,government_job,Medium

In [6]:
df['occupation'].unique()

array(['retired', 'freelancer', 'student', 'government_job',
       'business_owner', 'unemployed', 'private_job'], dtype=object)

In [7]:
df_feat = df.copy()

In [8]:
# Feature 1: BMI 
df_feat['bmi'] = df_feat['weight'] / (df_feat['height'] ** 2)

In [9]:
# Feature 2 : age group
def age_group(age):
    if age < 25:
        return 'young'
    elif 25 <= age < 45:
        return 'adult'
    elif 45 <= age < 60:
        return 'middle_aged'
    else:
        return 'senior'

In [10]:
df_feat['age_group'] = df_feat['age'].apply(age_group)

In [11]:
# Feaure 3 : Lifestyle risk
def lifestyle_risk(row):
    if row['smoker'] and row['bmi'] > 30:
        return 'high'
    elif row['smoker'] or row['bmi'] > 27:
        return 'medium'
    else:
        return 'low'

In [12]:
df_feat['lifestyle_risk'] = df_feat.apply(lifestyle_risk, axis=1)

In [13]:
tier_1_cities = ["Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata", "Hyderabad", "Pune"]
tier_2_cities = [
    "Jaipur", "Chandigarh", "Indore", "Lucknow", "Patna", "Ranchi", "Visakhapatnam", "Coimbatore",
    "Bhopal", "Nagpur", "Vadodara", "Surat", "Rajkot", "Jodhpur", "Raipur", "Amritsar", "Varanasi",
    "Agra", "Dehradun", "Mysore", "Jabalpur", "Guwahati", "Thiruvananthapuram", "Ludhiana", "Nashik",
    "Allahabad", "Udaipur", "Aurangabad", "Hubli", "Belgaum", "Salem", "Vijayawada", "Tiruchirappalli",
    "Bhavnagar", "Gwalior", "Dhanbad", "Bareilly", "Aligarh", "Gaya", "Kozhikode", "Warangal",
    "Kolhapur", "Bilaspur", "Jalandhar", "Noida", "Guntur", "Asansol", "Siliguri"
]

In [ ]:
# Feature 4 : City Tier
def city_tier(city):
    if city in tier_1_cities:
        return 'Tier 1'
    elif city in tier_2_cities:
        return 'Tier 2'
    else:
        return 'Tier 3'

In [14]:
df_feat['city_tier'] = df_feat['city'].apply(city_tier)

NameError: name 'city_tier' is not defined

In [17]:
df_feat.drop(columns= ['age', 'weight', 'height', 'smoker','city']), [['income_lpa', 'occupation', 'bmi', 'age_group', 'lifestyle_risk', 'city_tier', 'insurance_premium_category']]

(    income_lpa      occupation insurance_premium_category        bmi  \
 0      2.92000         retired                       High  49.227482
 1     34.28000      freelancer                        Low  30.189017
 2     36.64000      freelancer                        Low  21.118382
 3      3.34000         student                     Medium  45.535900
 4      3.94000         retired                       High  24.296875
 ..         ...             ...                        ...        ...
 95    19.64000  business_owner                        Low  21.420747
 96    34.01000     private_job                        Low  47.984483
 97    44.86000      freelancer                        Low  18.765432
 98    28.30000  business_owner                        Low  30.521676
 99    28.16664  government_job                        Low  27.688778

       age_group lifestyle_risk
 0        senior         medium
 1         adult         medium
 2         adult            low
 3         young           high
 4        senior         medium
 ..          ...            ...
 95        adult            low
 96        adult         medium
 97  middle_aged            low
 98        adult         medium
 99        adult         medium

 [100 rows x 6 columns],
 [['income_lpa',
   'occupation',
   'bmi',
   'age_group',
   'lifestyle_risk',
   'city_tier',
   'insurance_premium_category']])